name: carcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0 # make sure this is the latest version
  google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true # add this line
  assets:
    - assets/